# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://vladnik.github.io/
baseurl:
title: Engineer's Blog about Life, the Universe and Everything
author: Volodymyr Ladnik
description: >
  The answer to the great Question of Life,
  the Universe and Everything.
avatar: profile.jpg
email: vladnik.github@gmail.com
github:  vladnik
linkedin: volodymyrladnik
website: vladnik.github.io
google_maps: 'https://www.google.com/maps/place/San+Francisco'
city: San Francisco
country: California
skills:
  TypeScript: 5
  JavaScript: 5
  Golang: 4.5
  Ruby: 4.5
  Python: 4
  Scala: 3
  Swift: 2
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
