highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://vladnik.github.io
author: Volodymyr Ladnik

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl:
title: Volodymyr Ladnik's Resume
name: Volodymyr Ladnik
email: vladnik.github@gmail.com
email_full: mailto:vladnik.github@gmail.com
website: vladnik.github.io
website_full: https://vladnik.github.io
github: vladnik
stackoverflow: 11098769/volodymyr-ladnik
# tel: '+1'
# tel_full: tel:+1
google_maps: https://goo.gl/maps/dnFQ3ZkJX4PWaWTD7
# google_analytics: UA-69300817-1
skills:
  TypeScript: 5
  JavaScript: 5
  Hack: 4.5
  Golang: 4.5
  Ruby: 4
  Python: 4
  Scala: 3
  Swift: 2

# needed for travis-ci build
exclude: [vendor]
